#!/usr/bin/bash

# --- Configuration ---
APP_NAME="PyCloud"
# Use the same VENV path as the installer script
VENV_DIR="$HOME/.local/share/${APP_NAME}"
VENV_PYTHON="${VENV_DIR}/bin/python"

cd $VENV_DIR

source $VENV_DIR/bin/activate

python $VENV_DIR/run.py
